"""pets.py — virtual pets: merlion & donkey

Pixel style (truecolor): frames generated by emoji compositing (lion head + fish body + procedural water),
quantized to palette indices in pets_data.py — zero image-library deps at runtime.
Rendering: half-block ▀ (fg = upper pixel, bg = lower pixel) -> 2 truecolor pixels per char.
Animation: 3 frames (merlion water / donkey bounce) + rain-style row-by-row intro.
"""
import random

from rich.text import Text

from .pets_data import PETS_PIXEL

B36 = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN"

PETS = {
    "dolphin": {
        "mini": {"idle": ["🐬 ", "🐬~"], "running": ["🐬💦", "🐬🌊"]},
        "banner": "Dolphin reporting for duty",
    },
}


def choose_pet() -> str:
    return random.choice(list(PETS))


def _idx(ch: str):
    return None if ch == "." else B36.index(ch)


def render_pet(name: str, frame_idx: int = 0, reveal_rows: int | None = None) -> Text:
    """Render one frame (truecolor half-blocks). reveal_rows: only the first N char rows (intro)."""
    data = PETS_PIXEL[name]
    pal = data["palette"]
    frame = data["frames"][frame_idx % len(data["frames"])]
    out = Text()
    char_rows = (len(frame) + 1) // 2
    show = char_rows if reveal_rows is None else min(reveal_rows, char_rows)
    for r in range(show):
        up_row = frame[r * 2]
        low_row = frame[r * 2 + 1] if r * 2 + 1 < len(frame) else "." * len(up_row)
        for x in range(len(up_row)):
            u, l = _idx(up_row[x]), _idx(low_row[x])
            if u is not None and l is not None:
                ur, ug, ub = pal[u]
                lr, lg, lb = pal[l]
                out.append("▀", style=f"rgb({ur},{ug},{ub}) on rgb({lr},{lg},{lb})")
            elif u is not None:
                r_, g_, b_ = pal[u]
                out.append("▀", style=f"rgb({r_},{g_},{b_})")
            elif l is not None:
                r_, g_, b_ = pal[l]
                out.append("▄", style=f"rgb({r_},{g_},{b_})")
            else:
                out.append(" ")
        out.append("\n")
    return out


def intro_frames(name: str):
    """Intro animation: rain reveal (row by row) -> 2 animation cycles. Yields (Text, delay)."""
    char_rows = (len(PETS_PIXEL[name]["frames"][0]) + 1) // 2
    for k in range(1, char_rows + 1):
        yield render_pet(name, 0, reveal_rows=k), 0.05
    n = len(PETS_PIXEL[name]["frames"])
    for _cycle in range(2):
        for f in range(n):
            yield render_pet(name, f), 0.2
    yield render_pet(name, 0), 0.0
